### ISSUE TITLE
error while using Socket(URL).connect()

### ISSUE THREAD

**Issue by Scelester** [supabase-community/realtime-py#49]
Error : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

```

## Screenshots
Here is my script that produces the error
![image](https://user-images.githubusercontent.com/73174792/209563587-4a435382-997b-480f-82f5-1f94cce452ec.png)

## System information

- OS: Linux,Parrot os
- Version of supabase-client    ==    0.2.5
- Version of python == 3.9.2
- version of realtime == 0.0.5  

## Additional context
Also i cant seem to install realtime version 0.1.1a0 
```
ERROR: Could not find a version that satisfies the requirement realtime==0.1.1a0 (from versions: 0.0.2, 0.0.3, 0.0.4, 0.0.5)
ERROR: No matching distribution found for realtime==0.1.1a0`pip install realtime==0.1.1a0 
```

**Comment by Scelester** [comment]
here is the full error trackback:
```
Traceback (most recent call last):
  File "/home/scelester/Desktop/finland-backend/test.py", line 13, in <module>
    s.connect()
  File "/home/scelester/.virtualenvs/fin-land_rasp/lib/python3.9/site-packages/realtime/connection.py", line 90, in connect
    loop.run_until_complete(self._connect())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/scelester/.virtualenvs/fin-land_rasp/lib/python3.9/site-packages/realtime/connection.py", line 94, in _connect
    ws_connection = await websockets.connect(self.url)
  File "/home/scelester/.virtualenvs/fin-land_rasp/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/home/scelester/.virtualenvs/fin-land_rasp/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by Scelester** [comment]
nevermind i just removed "&vsn.." from the url and it stated working.
